[package]
name = "hashbrown-inc"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = { version = "0.15.2", default-features = false, git = "https://github.com/conradludgate/hashbrown", branch = "draining-table" }
polonius-the-crab = "0.4.2"

[dev-dependencies]
foldhash = { version = "0.1.2", default-features = false }
hdrhistogram = "7"
hashbrown = { version = "0.15.2", features = ["inline-more"], git = "https://github.com/conradludgate/hashbrown", branch = "draining-table" }

[[bench]]
harness = false
name = "insert"

[[bench]]
harness = false
name = "get"
